server/config/routes.rb
Rails.application.routes.draw do
  resources :logs
  root 'logs#index'

end

server/app/models/log.rb
class Log
  include MongoMapper::Document

  key :os_version, String
  key :app_version, String
  key :model, String
  key :device, String
  key :contents, String

  timestamps!
end

server/app/models/user.rb
class User
  include MongoMapper::Document

  key :name, String

end

server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

server/app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show, :edit, :update, :destroy]

  # GET /logs
  # GET /logs.json
  def index
    @logs = Log.all
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
  end

  # GET /logs/new
  def new
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs
  # POST /logs.json
  def create
    @log = Log.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    respond_to do |format|
      # if @log.save(log_params)
      #   format.html { redirect_to @log, notice: 'Log was successfully updated.' }
      #   format.json { render :show, status: :ok, location: @log }
      # else
      #   format.html { render :edit }
      #   format.json { render json: @log.errors, status: :unprocessable_entity }
      # end
      @log.model = log_params[:model]
      @log.contents = log_params[:contents]

      if @log.save
          format.html { redirect_to @log, notice: 'Log was successfully updated.' }
          format.json { render :show, status: :ok, location: @log }
      else
          format.html { render :edit }
          format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: 'Log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_params
      # key :os_version, String
      # key :app_version, String
      # key :model, String
      # key :device, String
      # key :contents, String
      params.require(:log).permit(:os_version, :app_version, :model, :device, :contents, :updated_at)
    end
end

server/app/helpers/application_helper.rb
module ApplicationHelper
end

server/app/helpers/logs_helper.rb
module LogsHelper
end

server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Honeycomb" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">HoneycombServer</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Copyright Honeycomb 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

server/app/views/logs/_form.html.erb
<%= form_for @log, :html => { :class => "form-horizontal log" } do |f| %>

    <% if @log.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @log.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :os_version %><br>
      <%= f.text_field :os_version %>
    </div>
    <div class="field">
      <%= f.label :app_version %><br>
      <%= f.text_field :app_version %>
    </div>
    <div class="field">
      <%= f.label :model %><br>
      <%= f.text_field :model %>
    </div>
    <div class="field">
      <%= f.label :device %><br>
      <%= f.text_field :device %>
    </div>
    <div class="field">
      <%= f.label :contents %><br>
      <%= f.text_field :contents %>
    </div>
    <div class="actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  logs_path, :class => 'btn btn-default' %>
    </div>



<% end %>

server/app/views/logs/edit.html.erb
<%- model_class = Log -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

server/app/views/logs/index.html.erb
<%- model_class = Log -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>OS</th>
      <th>App</th>
      <th>Model</th>
      <th>Code</th>
      <th>Contents</th>
      <th>Time</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= log.os_version %></td>
        <td><%= log.app_version %></td>
        <td><%= log.model %></td>
        <td><%= log.device %></td>
        <td><%= log.contents.slice(0, 20) %></td>
        <td><%= log.updated_at %></td>
        <td><%= link_to 'Show', log, :class => 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Edit', edit_log_path(log), :class => 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Delete',
                      log_path(log),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New',
            new_log_path,
            :class => 'btn btn-primary' %>

server/app/views/logs/new.html.erb
<%- model_class = Log -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

server/app/views/logs/show.html.erb
<%- model_class = Log -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <p>
    <strong>OS</strong>
    <%= @log.os_version %>
  </p>
  <p>
    <strong>App Version:</strong>
    <%= @log.app_version %>
  </p>
  <p>
    <strong>Model</strong>
    <%= @log.model %>
  </p>
  <p>
    <strong>Device</strong>
    <%= @log.device %>
  </p>
  <p>
    <strong>Contents</strong>
    <%= raw @log.contents.html_safe.gsub(/\n/, '<br />') %>  </p>
  <p>
    <strong>Updated</strong>
    <%= @log.updated_at %>
  </p>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              logs_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_log_path(@log), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              log_path(@log),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>